name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3

    
    - name: Install dependencie
    - working-directory: frontend
      run: npm ci
    
    - name: Build project
    - working-directory: frontend
      run: npm run build --if-present

    - name: Clear contents of /var/www/html
      run: sudo rm -rf /var/www/html/*

    - name: Copy dist folder to /var/www/html
      run: sudo cp -r frontend/dist/* /var/www/html
